pipeline {
    agent any
    
	environment {
        CICD_REPO = 'https://github.com/gotoa1234/JenkinsCICDConfigure.git'
        CICD_BRANCH = 'main'
    }
	
    stages {
        stage('Checkout CICD Config') {
            steps {
                // 檢出 CICD 配置到 分支 目錄
                dir('cicd') {
                    git branch: env.CICD_BRANCH,
                        url: env.CICD_REPO
                }
            }
        }
        
        stage('Execute Pipeline') {
            steps {
                // 執行對應環境的 Jenkinsfile
                load "JenkinMultiPipelineExample/${env.BRANCH_NAME}/Jenkinsfile"
            }
        }
    }
}